### ISSUE TITLE
ItemModel nicht komplett

### ISSUE THREAD

**Issue by antcedric91** [L2P-Academy/FIAE1_DnD#40]
In der ItemModel bitte:

- itemDurability in eine int statt String ändern. (Zeile 8 und 30)
- category in eine List<String> statt String ändern. (Zeile 31)

- Constuctor nicht komplett, isQuestItem und category fehlt bei der Datenanweisung (Zeile 37)

- zuletz dann die Getters und Setters anpassen. (Zeile 40 bis 97)

**Comment by weirdmustard** [comment]
Du hattest es jetzt nachbearbeitet, ja? Passt es nun so?

**Comment by weirdmustard** [comment]
Wir klären heut Nachmittag noch die Constructors.

Außerdem Frage an alle - was meinen wir mit Durability? Die Zahl der möglichen Hitpoints oder 100/100 Prozent?

**Comment by antcedric91** [comment]
Ich wäre dafür die Durability komplett wegzumachen, dann macht später quantity kein Stress

**Comment by weirdmustard** [comment]
Durability is raus.
