### ISSUE TITLE
Error mit NodeList 

### ISSUE THREAD

**Issue by christian-gassmann** [L2P-Academy/FIAE1_DnD#85]
Ich wollte NodeList verwenden um die Daten von den XML Datein zu lesen. 

Jetzt ist es so, dass ich 2 Errors bekomme, wenn ich NodeList und Node importiere. Scheinbar ist das Problem im Buildpath, kenne mich da aber nicht aus.

![grafik](https://github.com/L2P-Academy/FIAE1_DnD/assets/168087906/ec3a43ad-32ad-47fd-a906-2652f25b1738)

![grafik](https://github.com/L2P-Academy/FIAE1_DnD/assets/168087906/5c091316-865e-44d1-960f-3b57e27b5eaf)

![grafik](https://github.com/L2P-Academy/FIAE1_DnD/assets/168087906/82f07587-88fe-4752-a456-23be9ab4aee5)

**Comment by L2P-Academy** [comment]
## Mögliche Lösungen:

1. Build-Path neu festlegen, das hatten auch schon andere Teilnehmer, alternativ Neuinstallation von allem inklusive Java an sich - hier einfach mal googlen, am besten den Fehler kopieren oder chatGPT fragen hilft auch manchmal bei so etwas
2. Gehen Sie ansonsten mal auf Project-> Clean..., das kann helfen
3. haben Sie die Nodelist oben importiert? -> import org.w3c.dom.NodeList;
4. Syntax beachten, hier noch mal das Beispiel vom Zoo - XMLController, aber die kennen Sie wahrscheinlich schon (insbesondere muss an das try/catch gedacht werden)
![grafik](https://github.com/L2P-Academy/FIAE1_DnD/assets/161337219/98daa20d-bc4a-48cd-992b-f13e4555696f)

Ich habe soeben mal die NodeList bei mir lokal erstellt, die scheint auch zu funktionieren, inklusive Import. Also vermutlich ist irgendetwas bei Ihnen nicht richtig installiert/eingestellt.

Falls das alles nichts hilft, schauen wir es uns am Freitag an, genießen Sie den freien Tag :)

**Comment by christian-gassmann** [comment]
Clean hat geholfen, danke

**Comment by christian-gassmann** [comment]
Close hat geholfen, danke
