### ISSUE TITLE
ItemModel bräuchte getter & setter für Gold

### ISSUE THREAD

**Issue by Rakinos89** [L2P-Academy/FIAE1_DnD#86]
Glaube zumindest das ich in ItemModel g&s brauche
oder kann man das iwie anders lösen??

**Comment by L2P-Academy** [comment]
Die Getter und Setter haben Sie schon -> dafür getQuantity und setQuantity verwenden, um die Anzahl von Gold zu ändern (Sie müssen die Getter und Setter dann auf dem entsprechenden Item aufrufen, also etwa beim Ausgeben von 5 Gold:
int münzen = gold.getQuantity() - 5;
setQuantity(münzen);
